### ISSUE TITLE
Import NDK balíčku - klient donekonečna načítá

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-admin-client#1]
Když chybí kořenový adresář pro NDK import, klient donekonečna točí kolečkem, ačkoli API vrací správnou chybu.

**Comment by rzeh4n** [comment]
Opraveno, od verze 1.1.3 se v takovém případě nezobrazí výběr podadresáře a další ovládací prvky. Ale zobrazí se chyba informující o tom, který konkrétní adresář chybí.
