### ISSUE TITLE
Chyba při indexaci

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-admin-client#10]
https://admin.k7-test.mzk.cz/processes/280258

cílem bylo reindexovat všechny zvukové dokumenty které nebyly indexované nebo byly zastaralé. V chybovém výstupu je řada výjimek. @rzeh4n můžeš se na ne podívat?

**Comment by rzeh4n** [comment]
U některých zvukových objektů nejsou dostupné samotné zvuky (wav/mp3/ogg) na audio servru.
Např.: z foxml uuid:e86ca43b-3a90-4792-b356-831a5b0af2ff:

```
    <foxml:datastream ID="WAV" STATE="A" CONTROL_GROUP="E" VERSIONABLE="true">
        <foxml:datastreamVersion ID="WAV.0" LABEL="Wav version of this audio track" CREATED="2015-10-26T13:38:28.000Z" MIMETYPE="audio/wav">
            <foxml:contentLocation TYPE="URL" REF="http://audioserver.mzk.cz/mzk01/000/471/242/e86ca43b-3a90-4792-b356-831a5b0af2ff.wav"/>
        </foxml:datastreamVersion>
    </foxml:datastream>
    <foxml:datastream ID="MP3" STATE="A" CONTROL_GROUP="E" VERSIONABLE="true">
        <foxml:datastreamVersion ID="MP3.0" LABEL="Mp3 version of this audio track" CREATED="2015-10-26T13:38:28.000Z" MIMETYPE="audio/mpeg">
            <foxml:contentLocation TYPE="URL" REF="http://audioserver.mzk.cz/mzk01/000/471/242/e86ca43b-3a90-4792-b356-831a5b0af2ff.mp3"/>
        </foxml:datastreamVersion>
    </foxml:datastream>
    <foxml:datastream ID="OGG" STATE="A" CONTROL_GROUP="E" VERSIONABLE="true">
        <foxml:datastreamVersion ID="OGG.0" LABEL="Ogg Vorbis version of this audio track" CREATED="2015-10-26T13:38:28.000Z" MIMETYPE="audio/ogg">
            <foxml:contentLocation TYPE="URL" REF="http://audioserver.mzk.cz/mzk01/000/471/242/e86ca43b-3a90-4792-b356-831a5b0af2ff.ogg"/>
        </foxml:datastreamVersion>
    </foxml:datastream>
```

Všechno tohle vrací 403:
http://audioserver.mzk.cz/mzk01/000/471/242/e86ca43b-3a90-4792-b356-831a5b0af2ff.wav 
http://audioserver.mzk.cz/mzk01/000/471/242/e86ca43b-3a90-4792-b356-831a5b0af2ff.mp3
http://audioserver.mzk.cz/mzk01/000/471/242/e86ca43b-3a90-4792-b356-831a5b0af2ff.ogg

Indexer tu zvukovou stopu používá ke zjištění délky v sekundách, ta se indexuje. V těchhle situacích se objekty tracků zaindexují, jen bez té délky. 
O tu indexaci zas tolik nejde, hlavně tyhle věci nejdou přehrát!

Spustil jsem to [znovu](https://admin.k7-test.mzk.cz/processes/298571), vypadá to, že teď by těch problematických věcí mělo trochu víc.

**Comment by zabak** [comment]
@r2it-git můžeš to prosím zkontrolovat a tohle issue buď aktualizovat nebo zavřít?

**Comment by zabak** [comment]
OK, zde zavírám, budeme řešit interně.
