### ISSUE TITLE
ČDK - Prirotizace knihoven

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius-admin-client#105]
Umožnit zobrazit akutální mapování z isuse  [49](https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/49)

- [x] pridat pole do tabulky (html, ts)
- [x] lokalizace noveho pole
- [x] vytvorit novou komponentu pro dialog
- [x] vytvorit metodu pro dialog s predanim parametru
- [x] vytvorit tabulku zobrazeneho mapovani pro konkretni knihovnu dle zadani - obsah tabulky zobrazit na zaklade parametru
- [x] lokalizace dialogu a tabulky
- [x] osetrit no results
- [x] test

**Comment by pkudela** [comment]
hotovo, @pavel-stastny prosim otestuj a prirad tomu label pristi verze

**Comment by pkudela** [comment]
@pavel-stastny verzi jsem oznacil, tak jen prosim o kontrolu.
