### ISSUE TITLE
Vyřešit konfiguraci Doporučených dokumentů

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-admin-client#11]
Na knihovny.cz máme tzv. inspirační seznamy - jsou to sady předvybraných dokumentů, ze kterých se na hlavní stránku při každé návštěvě uživatele vybere náhodně několik, takže jsou tam pokaždé jiné. Na hlavní stránce jsou zobrazeny až 3 takové seznamy, které se dají dle potřeby měnit, těch seznamů existuje víc, některé mají speciální vlastnosti (např reklamní okénko nebo seznam druhů dokumentů)

Zde by základem mohla být nějaká speciální virtuání sbírka nebo několik sbírek.

**Comment by honza-rychtar** [comment]
Tohle by mělo vycházet z nového návrhu hlavní stránky. To by mělo vycházet z diskuze kurátorů a lidí z UX.

**Comment by zabak** [comment]
Doplnit do adminu možnost nastavovat seznamy na hlavní stránku, poskytované přes API.  Přenesení z konfigurace web klienta. Zachovat možnost, že klient lokální konfigurací přebije to co poskytuje api

**Comment by zabak** [comment]
Zde zavírám, řešeno v https://github.com/ceskaexpedice/kramerius-web-client/issues/711
