### ISSUE TITLE
Podpora OAI v administracnim rozhrani

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius-admin-client#119]
- [x] na strance repozitar vytvorit novou zalozku "oai" a k ni potrebny route
- [x] v zalozce "oai" vytvorit input "Implicitni set" s moznosti editace a ulozeni
- [x] v zalozce "oai" vytvorit tabulku: nazev, popis, filter, akce => editovat
- [x] pro akci editovat vytvorit modal dialog
- [x] preklady
- [x] pripravit snackbary pro vsechny metody v ramci zalozky "oai"
- [x] u inputu implicitni set pridat tlacitko "Pridat novy set" + k tomu potrebny dialog + preklady + snackbar
- [x] u tabulky pridat sloupec pro smazani zaznamu
- [x] priprava metod pro vsechny vyse uvedene akce

**Comment by pkudela** [comment]
@pavel-stastny hotovo, pripraveno, zbyva dodelat posledni bod
