### ISSUE TITLE
Hromadné mazání proběhlých procesů

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius-admin-client#126]
Zdravím,

nepřišel jsem na způsob, jak hromadně smazat již proběhlé procesy (bez ohledu na stav).

Aktuálně lze proběhlé procesy mazat pouze po jednom, klikáním na ikonu koše. Což je použitelné velmi omezeně, zvláště v případě, kdy proběhly nějaké masivní akce, např. reindexace podle modelu.

V takovém případě se v seznamu procesů objeví stovky, nebo klidně i tisíce procesů, a pak je prakticky nemožné v nějakém reálném/rozumném čase se záznamů o proběhlých procesech zbavit (kromě smazání přímo v databázi, ale to není úplně optimální pro běžné aplikační adminy).

Něco mi tedy uniká, nebo opravdu nelze hromadně proběhlé procesy mazat?

Díky, MD

**Comment by mduda100871** [comment]
Zdravím,

přidávám další problémy na které jsem narazil:

- ve formuláři pro indexaci podle podle modelu, chybí u některých typů popisky, musím to vždy ručně dodávat do konfigurace klienta a je to nepříjemné:

![admin-00](https://github.com/ceskaexpedice/kramerius-admin-client/assets/8750622/0a117bf3-095f-449b-8110-dea3064820f8)

- nelze odstranit, resp. jsem nepřišel na to, jak odstranit lokální licenci se seznamu licencí, přestože už není využívána.

MD

**Comment by pavel-stastny** [comment]
@mduda100871 U lokální licence je ikonka editace a mazání. 

![image](https://github.com/ceskaexpedice/kramerius-admin-client/assets/675753/48c7921b-af6c-49a5-b2e8-7f5b1e7471bb)

**Comment by pavel-stastny** [comment]
Je možné, že není nadefinovaný acronym knihovny: 
![image](https://github.com/ceskaexpedice/kramerius-admin-client/assets/675753/5c4cf8a1-90b3-420a-9191-22a0e70b186c)


Pokud ne, pak je nutnto definovat konf. proměnnou: 

`acronym=inovatika`

**Comment by mduda100871** [comment]
Díky, funguje, jen pro úplnost doplním, že properta je umístěna v `~/.kramerius4/configuration.properties`.

Issue zatím neuzavírám dokud se nějak nevyřeší i ostatní body.

MD

**Comment by mduda100871** [comment]
Ve formuláři pro správu oprávnění chybí popisky pro dvě akce, viz screenshot:

![admin_00](https://github.com/ceskaexpedice/kramerius-admin-client/assets/8750622/9b13025b-abaf-4f7a-a83e-4f10bab04644)

**Comment by pkudela** [comment]
@pavel-stastny je to pripravene, prosim, dopln funkcionalitu

**Comment by pavel-stastny** [comment]
@mduda100871 Přidána možnost hromadného mazání procesů z admin prostředí  

![image](https://github.com/user-attachments/assets/02c9816f-d6e9-4689-8f78-f96797e45bf4)

Pro automatické odmazávání procesů vznikne procec, který bude mít možnost smazat starší, doběhnuté procesy dle zadaného data.
