### ISSUE TITLE
Ve wiki dokumentaci je chybný odkaz na stránku s instalací a konfigurací

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius-admin-client#133]
Mám jen maličkou připomínku - na wiki je špatný odkaz pod tlačítkem Instalace a konfigurace. Vede to na stránku "Administrace přehled". Mělo by to vést sem (předpokládám): https://github.com/ceskaexpedice/kramerius-admin-client/wiki/Instalace-a-konfigurace

obrázek:
![image](https://github.com/user-attachments/assets/62e9173b-6b91-4af5-bcea-c79f2e768d15)

[Instalace a konfigurace](https://github.com/ceskaexpedice/kramerius-admin-client/wiki/Administrace-p%C5%99ehled)

**Comment by vlahoda** [comment]
Diky za upozorneni, opraveno.
