### ISSUE TITLE
Hromadné přidávání dokumentů do sbírky

### ISSUE THREAD

**Issue by marketakrutska** [ceskaexpedice/kramerius-admin-client#14]
Chtěla bych navrhnout přidání funkce, díky které by bylo možné přidat více uuid najednou do virtuální sbírky. Nyní to v MZK děláme přes tu naši aplikaci Fofola a bylo by fajn to mít i v K7. Funguje to tak, že nahraju seznam uuid a zvolím si sbírku, do které se to má přidat (vybírám si z nabídky existujících sbírek, nepíšu to tam ručně).
Kromě přidávání můžu uuid ze sbírky i odstranit. To by bylo v K7 také fajn, i když to není tak důležité. 
![screenshot-fofola infra mzk cz-2022 04 26-15_28_34](https://user-images.githubusercontent.com/43740512/165311649-f4ae5836-3c99-4e5f-997a-a625156c0e02.png)

**Comment by honza-rychtar** [comment]
Ok, přidáme.

**Comment by marketakrutska** [comment]
Super, díky moc!

**Comment by zabak** [comment]
@honza-rychtar tohle bychom potřebovali vyřešit co nejrychleji, bylo by to možné?

**Comment by marketakrutska** [comment]
Hromadné přidávání již funguje, což je super. Odstraňování dokumentů ze sbírky funguje teď jen jednotlivě. Je otázka, nakolik by se používalo i hromadné odstraňování ze sbírky. Asi se to moc často stávat nebude. 
Issue zavírám, případně se v budoucnu založí issue na hromadné odstraňování, kdyby se to ukázalo jako podstatné.
