### ISSUE TITLE
Nelze přidávat sbírky do sbírek

### ISSUE THREAD

**Issue by marketakrutska** [ceskaexpedice/kramerius-admin-client#15]
Nějak nám zmizela funkce přidání sbírky do jiné sbírky. Mám oprávnění sbírku upravovat, ale nemůžu ji přidat do jiné sbírky. Nejde to ani jiným lidem u nás, dříve nám to šlo. Nebo tam ta funkce je a my jsme si jí jen nevšimli? 
![image](https://user-images.githubusercontent.com/43740512/166647168-b3197659-263d-41ab-965f-e11090f5220e.png)
![image](https://user-images.githubusercontent.com/43740512/166647244-23c0e3ce-b371-48e5-b5f8-55f17db60d25.png)
![image](https://user-images.githubusercontent.com/43740512/166647285-d5673fe3-d0f5-4f99-8350-2cbaacba52bd.png)

Jo a ještě jsme si všimli malého překlepu u seznamu sbírek. Je tam "Puze" namísto "Pouze".
![image](https://user-images.githubusercontent.com/43740512/166647654-9296180d-0c00-402d-b27f-a15ebc6dd55b.png)

**Comment by zabak** [comment]
@honza-rychtar tohle bychom taky potřebovali vyřešit poměrně rychle. Můžeš to prosím udělat?

**Comment by marketakrutska** [comment]
Toto je již opravené, takže issue zavírám.
