### ISSUE TITLE
Chybí mazání dokumentů

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-admin-client#2]
V K7 adminovi jsem nikde nenašla mazání dokumentů. Není to sice běžně používaná funkcionalita, ale hodila by se tam. Jednou za čas je třeba mazat případné duplicity apod.

**Comment by vlahoda** [comment]
K mazani dokumentu je v Krameriovi proces delete, ktery staci spustit. Aby to ale bylo z uzivatelskeho hlediska pohodlne, potrebujeme propojit uzivatelskeho a administratorskeho klienta, aby v uzivatelskem klientovi slo k aktualne vybranym dokumentum otevrit kontextove menu a z nej spoustet administratorske akce. Napriklad mazani. Nebo nastaveni public/private. Nebo cokoli jineho. Je potreba domluvit nejake flexibilni rozhrani, aby se kvuli pridani nove administratorske funkce nemusel pokazde modifikovat standardni klient. @pavel-stastny k tomu ma uz pripravene reseni

**Comment by honza-rychtar** [comment]
@vlahoda Ok, teď jsou z uživatelského klienta spouštět akce pro vybraný objekt nebo pro vybrané objekty z výsledků hledání.
- Nastavení public/private
- Nastavení reprezentativní strany
- Reindexace
- Přidání/odebrání objektů do/z sbírky

Zavoláme si (@pavel-stastny @vlahoda  @rzeh4n @honza-rychtar ) k tomu jak a jestli to připravit nějak flexibilně. Ony jsou ty administrátorské akce dost odlišné v tom, jak s nimi klient zachází.

![Snímek obrazovky 2022-04-22 v 11 37 36](https://user-images.githubusercontent.com/1178142/164680289-7d1b273c-7d2b-433e-9c4e-80b4cb936ea3.png)
![Snímek obrazovky 2022-04-22 v 11 37 20](https://user-images.githubusercontent.com/1178142/164680293-887db376-440d-4604-b78f-29a4b11ac393.png)
![Snímek obrazovky 2022-04-22 v 11 37 10](https://user-images.githubusercontent.com/1178142/164680297-6ffa783b-943a-4dba-93dd-b733f376fe57.png)

**Comment by rzeh4n** [comment]
Já ten proces na mazání ještě prověřím přes admin rozhraní. Nejsem si jistý, jestli to bude korektně fungovat, proces může spoléhat na vnitřní servisy napojené na starý index.
Taky se některé věci koncepčně změnily, např. princip "indexace objektu X ve stejném stavu repozitáře dopadne stejně bez ohledu na zaindexovanost jiných objektů" dřív neplatil vždy (závislost na indexu při indexaci).
Pojďme si možná ujasnit, co přesně chceme od procesu mazání. Já bych to viděl nějak takhle:

- proces "smazat objekt X" odstraní jak z indexu tak z repozitáře X, všechny jeho (vlastní) potomky rekurzivně (celý vlastní strom)
- proces neodstraní nevlastní potomky, takže třeba "smazat sbírku S" nesmaže dokumenty v S, ani jiné sbírky v S
- anebo "smazání článku Č" neodstraní stránky, na které se článek odkazuje nevlastní vazbou "isOnPage", stejně tak s model:picture
- je potřeba v indexu reflektovat licence a náležitost do sbírky (po smazání sbírky)

Nejasnosti:
- co obrázky v externím image serveru? Taky nějak řešit mazání?

**Comment by pavel-stastny** [comment]
@honza-rychtar @rzeh4n @vlahoda Já bych doporučil nejdříve ten call

**Comment by zabak** [comment]
Zrovna mazání je operace, u které nechceme aby byla úplně snadná, aby někdo něco nesmazal omylem, třeba jen proto, že se překlikne. 

Za MZK by jako první krok (z hlediska admin rozhraní) stačilo přidat do položky Repozitář tlačítko, přes které by bylo možné zadat jedno nebo více uuid pro smazání, podobně jako třeba u reindexace. To je minimální funkční požadavek, blokující přechod na K7. 

@rzeh4n u mazání obrázků z imageserveru (nebo zvuků, pdf, epubů) by bylo vhodné mít nějakou volbu typu "smazat i obrázky z imageserveru". 

Nice to have: bylo by dobré aby bylo kurátorovi jasné, co vlastně maže, když zadává mazání. Tj. že by mu to třeba po zadání smazání jednoho uuid řeklo "chystáte se mazat 1 titul, 5 ročníků, 100 issues, 5000 stránek a 5000 obrázků".

**Comment by honza-rychtar** [comment]
Mazání je dostupné buď na úrovni repozitáře přes zadání seznamu pidů nebo přímo u vybraného objektu.
Mazání pak má dvě volby 
- jen objekt - smaže se pouze vybraný objekt) 
- celý podstromě - smaže se celý podstrom a synchronizují se příznaky sbírek a licencí, které to mohlo ovlivnit.

Vše je pak ještě popsané v dialogu s potvrzením.

Ještě trochu učešeme ty texty, které teď koukám, se nám rozjely mezi repozitářem a objektem.

**Úroveň repozitáře**
<img width="1528" alt="Snímek obrazovky 2022-08-04 v 12 13 20" src="https://user-images.githubusercontent.com/1178142/182824325-07774c58-b6c0-4edd-bfc7-d5a56e574553.png">

<img width="1023" alt="Snímek obrazovky 2022-08-04 v 12 14 08" src="https://user-images.githubusercontent.com/1178142/182824334-86f18d92-131b-4a69-a892-e68cf361f88f.png">

<img width="1043" alt="Snímek obrazovky 2022-08-04 v 12 14 58" src="https://user-images.githubusercontent.com/1178142/182824339-ae5ba0a1-a581-416b-bf4e-f4a752c0e5f8.png">

**Úroveň objektu**
<img width="1488" alt="Snímek obrazovky 2022-08-04 v 12 16 25" src="https://user-images.githubusercontent.com/1178142/182824343-8b3eac96-d522-48e9-b3b5-51182497e8b7.png">

<img width="1001" alt="Snímek obrazovky 2022-08-04 v 12 27 21" src="https://user-images.githubusercontent.com/1178142/182825699-7c9730b0-5c6d-46b6-b847-610481174a84.png">

<img width="994" alt="Snímek obrazovky 2022-08-04 v 12 27 44" src="https://user-images.githubusercontent.com/1178142/182825694-c1b613c7-2bdb-45be-93e4-dfd21c88b2d4.png">

**Comment by annie-cz** [comment]
Nemám aktuálně žádné informace o tom, že by něco nějak nefungovalo. Díky, prozatím můžeme asi zavřít. Kdyby něco, ozvali bychom se.
