### ISSUE TITLE
Propisování licenčních atributů do podobjektů

### ISSUE THREAD

**Issue by stanislavteplik** [ceskaexpedice/kramerius-admin-client#22]
Dobrý den,
po posledním updatu jsme si všimli problému s novými zámečky v uživatelském klientovi. Pokud dám periodiku licenci dnnt, tak se zámeček ukáže pouze na úrovni periodika a na úrovni ročníku a níže nikoliv. Pokud si otevřu ročník/číslo/stránku daného periodika v admin rozhraní, tak u něj přiřazenou licenci dnnt také nevidím.

Bylo by možné, aby se přiřazování licence z admin prostředí propisovalo i do všech podobjektů? 

Čtenář s právy dnnt má normálně k peridiku přístup. Jde o problém zobrazování správných zámků u jednotlivých licencí.

Děkuji.

**Comment by honza-rychtar** [comment]
V uživatelském klientovi jsme to upravili v nové verzi v2.3.7 (https://github.com/ceskaexpedice/kramerius-web-client/issues/538)
Zkuste na vašich datech tady http://dk.kramerius.org/svkpk/search

V Admin klientovi se teď zobrazují pouze licence přiřazeny přímo objektu (nezděděné).
Přidáme tam i zobrazení licencí, které má vybraný objekt zděděné. Ty se nebudou dát editovat (dědí se automaticky), ale bude z toho jasné, že objekt licenci dědí z některé nadřazeného objektu a že reálně se na něj licence aplikuje.

**Comment by stanislavteplik** [comment]
Dobrý den, hlásím, že opraveno v klientovi a i na dk jsou licence, tak, jak mají. Děkujeme
