### ISSUE TITLE
V k7-test na MZK se nenacita seznam sbirek

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-admin-client#29]
V k7-test na MZK se nenacita seznam sbirek, problem je zrejme zpusoben tim, ze v ulozisti chybi FOXML objekt uuid:1063d11b-02fb-44fe-94ef-ba64da748ff7, kvuli tomu spadne proces nacitani sbirek s chybou 500 a nenactou se zadne.
V logu je tento retez vyjimek:
cz.incad.kramerius.rest.apiNew.admin.v70.collections.CollectionsResource.getCollections object not consistently found in storage: uuid:1063d11b-02fb-44fe-94ef-ba64da748ff7

cz.incad.kramerius.fedora.om.RepositoryException: object not consistently found in storage: uuid:1063d11b-02fb-44fe-94ef-ba64da748ff7

**Comment by pavel-stastny** [comment]
@marketakrutska Na MZK by měla být nová verze již nasazena.

**Comment by rzeh4n** [comment]
Vyzkoušel jsem, funguje. Byť se to načítá docela dlouho (5s), ale to je jiný problém - dotaz zjišťující dostupné akce pro všechny sbírky.

**Comment by marketakrutska** [comment]
Pravda, už se to načítá. Mě se to načítá tak 10 vteřin, proto jsem původně myslela, že to ještě nejede. Děkuji za opravu!

**Comment by pavel-stastny** [comment]
@rzeh4n Chyba se znovu opakuje:

22-Sep-2022 09:17:09.059 SEVERE [ajp-nio-127.0.0.1-8009-exec-503] cz.incad.kramerius.rest.apiNew.admin                                                              .v70.collections.CollectionsResource.getCollections object not consistently found in storage: uuid:106                                                              3d11b-02fb-44fe-94ef-ba64da748ff7
        cz.incad.kramerius.fedora.om.RepositoryException: object not consistently found in storage: uu                                                              id:1063d11b-02fb-44fe-94ef-ba64da748ff7

**Comment by marketakrutska** [comment]
Mohla bych se prosím zeptat, jak to vypadá s opravou? Se sbírkami bychom potřebovali pracovat.

**Comment by pavel-stastny** [comment]
@marketakrutska @rzeh4n  Mělo by už fungovat s tím omezením, že to trvá 10s. To bude řešeno v rámci issue  #31.

**Comment by marketakrutska** [comment]
Super, díky moc, už se mi to načítá. Issue bych zavřela, ale asi na to nemám právo.

**Comment by marketakrutska** [comment]
Problém se opakuje. Asi jsem to zase udělala já při vytváření sbírek, ale netuším, co přesně dělám špatně.

**Comment by pavel-stastny** [comment]
@marketakrutska Už by nemělo. V příští verzi bude zahrnuta oprava. (Tohoto i issue 31)

**Comment by pavel-stastny** [comment]
Již by se nemělo dít. V případě potřeby znovu otevřte.
