### ISSUE TITLE
Otázka: Vyhledávání dokumentů v admin klientovi

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-admin-client#3]
Ve starém admin klientovi byla možnost jako admin přímo procházet a vyhledávat věci v dokumentech. Počítá se zde s podobnou funkcionalitou? 

Oceňuji nástroje na hromadné opravy, ale pokud by na správu dokumentů bylo jen toto, tak to pro kurátora v podstatě znamená mít nutně dva monitory a ručně si kopírovat uuid z DK a předávat je pak do admin klienta. Pomohlo by, kdyby v admin klientovi byla zároveň i stará cesta, abychom jen zaklikali příslušné dokumenty a provedli s nimi nějakou akci.

![image](https://user-images.githubusercontent.com/43028501/152961509-97baae19-3f94-46f2-b02b-b88eacbfb100.png)

Nebo se počítá s tím, že admin klient bude určený pouze na hromadné akce a na drobné úpravy bude sloužit přihlášení pomocí admin účtu v běžném rozhraní Krameria? (tužtička apod.) A pokud to tak je, co všechno bude součástí admin klienta a co všechno admin účtu v DK?

**Comment by honza-rychtar** [comment]
Stačí mít vyhledávání v DK, pokud přibudou hromadné úpravy i uvnitř dokumentu (https://github.com/ceskaexpedice/kramerius-web-client/issues/530) a kromě současných hromadných úprav (nastavení viditelnosti, reindexace, přidání/odebrání do/ze sbírky) přibude ještě přidání/odebrán licence?

**Comment by annie-cz** [comment]
Ještě bych dala přidání a odebrání donátora a bude snad už vše. :)

**Comment by annie-cz** [comment]
Zde chybí poslední požadavek, přesunuto společně s #27 do web klienta:

https://github.com/ceskaexpedice/kramerius-web-client/issues/645
