### ISSUE TITLE
Hromadné vyřazení dokumentů ze sbírky

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-admin-client#34]
Při hromadné editaci dokumentů uvnitř sbírky nemám možnost je ze sbírky vyřadit. Nabízí se jen možnost je do té sbírky, ve které už jsou, zařadit znovu. 

![image](https://user-images.githubusercontent.com/57805328/194101033-3e39f82d-758b-407d-971d-9e8960bd8797.png)

**Comment by annie-cz** [comment]
Stejný problém. 

Kromě toho mi nepřijde úplně šťastné, aby při pouhém kliknutí na plus nebo mínus se rovnou rozjel proces. Ocenila bych asi spíš kliknout na plus/mínus a pak ještě nějakou hlášku "zařadit dokument do sbírky/vyřadit dokument ze sbírky", než to tam takhle napálit rovnou.

**Comment by D-Benes** [comment]
A je také matoucí, že se do administrace sbírek vstupuje přes tlačítko _Změna viditelnosti_.

**Comment by annie-cz** [comment]
Jinak tu mám update.. aktuálně z klienta nelze odstranit ze sbírky žádný dokument, což si myslím, že bude bug. Vůbec se mi nezobrazí ani to mínus, tj. proces to nevezme, donekonečna se točí kolečko a proces se nespustí, protože akce takto nedává smysl (takto to vypadá, jako bych klientovi říkala, že má zařadit ty stejné dokumenty do sbírky). Nepomůže ani nezatrhnout všechny dokumenty a nebo jen jeden - vypadá to, že klient to aktuálně neumí. 

<img width="695" alt="image" src="https://user-images.githubusercontent.com/43028501/207440257-e80d8d30-c612-4e97-ac90-4e55cf94e32a.png">


A mám tu ještě další problém jako bonus - nelze hromadně odstranit dokumenty ani v admin klientovi. Resp. jde, ale jen po jednotlivých kliknutích na křížek. Právě jsem tuhle operaci dělala u sbírky, jejíž obsah jsem potřebovala ze sbírky vyřadit ... a jednalo se o 119 dokumentů. No ... nebylo to moc radostné. :)

<img width="931" alt="image" src="https://user-images.githubusercontent.com/43028501/207439250-14de14b6-065d-4a51-883a-71966a1f7fd2.png">

**Comment by pkudela** [comment]
@pavel-stastny hotovo:

- checkboxy doplneny
- btn pro smazani vybranych sbirek
- potvrzovaci dialog pro smazani sbirek
- preklady atd.

todo:

- propojit checkboxy s buttonem pro smazani vybranych sbirek
- dodelat metodu potvrzovaciho dialogu smazani vybranych sbirek

**Comment by pavel-stastny** [comment]
@pkudela Potvrzovaci dialog ma ted dve moznosti, jit na seznam procesu nebo zustat na sbirkach.  Poprosil bych o lokalizaci.

**Comment by pkudela** [comment]
mazadni vybranych sbirek je hotove

**Comment by pkudela** [comment]
@honza-rychtar v K7 admin klientovi je toto hotovove, vytvoril jsem na to dedikovane issue -> #77 , cili toto necham otevrene pro jen pro tebe.

**Comment by annie-cz** [comment]
Přesun issue do web klienta, viz: https://github.com/ceskaexpedice/kramerius-web-client/issues/644
