### ISSUE TITLE
Repozitář → Hromadné úpravy dat

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-admin-client#35]
Při hromadné úpravě dat se mi nedaří přidat licenci víc než jednomu dokumentu. Když tam vyplním jen jedno UUID, tak to proběhne v pořádku, ale když jich do okna zadám víc, tak po potvrzení dialogového okna vyskočí hláška, že se naplánování procesu nepovedlo.

U mazání a nastavování public/private to ale funguje správně.

Díky.

FK

**Comment by kerschfilip** [comment]
@pavel-stastny zkoušel jsem to a stále mi to vrací tu stejnou chybu

Testoval jsem na k7Admin - verze: 1.4.0 - commit: gef93035, jádro verze: 7.0.14 - commit: e0136

**Comment by r2it-git** [comment]
Zdravím, 
za MZK by som chcel informovať, že máme veľmi podobný problém (podľa mňa ten istý) až na to, že nastáva pri všetkých hromadných úpravach a pri reindexáciach. Pri spracovaní nejakých 50 uuid sa väčšinou tie procesy naplánujú, pri vyšších číslach vyskočí hláška a naplánujú sa buď všetky alebo len niektoré alebo žiaden proces, ako kedy + záleži aj čím vyžší počet tým menej pravdepodobné, že sa niečo naplánuje. 
Momentálne otestované na jadro: verze: 7.0.15 - commit: 04e8e, admin: verze: 1.4.0 - commit: gef93035.
Nakoniec by som chcel ešte povedať, že v K5 bežne dávkujem procesy do 10.000 uuids a očakávali by sme, že podobné plánovanie bude možné aj v K7.
Ďakujem.
Róbert Randiak, MZK

**Comment by pavel-stastny** [comment]
@kerschfilip Problém nastavování licencí byl na jádře, vyřešeno komitem [80b5ed8](https://github.com/ceskaexpedice/kramerius/commit/80b5ed839fdd129c8e0a03f38c2559eb5490d976)

**Comment by pkudela** [comment]
Nasazeno na testovacim serveru -> https://admin.k7.inovatika.dev
