### ISSUE TITLE
Vkládání obrázků do popisu sbírky

### ISSUE THREAD

**Issue by marketakrutska** [ceskaexpedice/kramerius-admin-client#36]
Mám dotaz. Jaký je správný postup pro vkládání obrázků do popisu sbírky? Mně se to tam povedlo "přetáhnout" z přílohy mailu. Ale problém je, že ostatním lidem se to nezobrazuje. Jak to tam mám vložit, aby to fungovalo správně? Díky.
![image](https://user-images.githubusercontent.com/43740512/194313922-151a2b0d-d1a1-4094-ab2d-90a3b272d354.png)

_______________________________

![image](https://user-images.githubusercontent.com/43740512/194313951-31b9513d-4f4f-4e44-bdbb-0af45127fc4e.png)

**Comment by marketakrutska** [comment]
Chtěla bych se připomenout s tímto issue. Do některých sbírek bychom potřebovali vložit logo projektu, ale nyní nám to nefunguje. Je nějaký postupu, jak se to má dělat správně?

**Comment by pavel-stastny** [comment]
@marketakrutska Nyní jedíná možnost jak dostat obrázek do textu je přes schránku.  Funguje v Chrome a Edge.  Pokud dáte na obrázku v prohlížeči volbu "Kopírovat obrázek" a v editoru dáte "Vložit", objeví se Vám v textu. 

( Poznámka: Obrázek je pouze prolinkován)

**Comment by pavel-stastny** [comment]
@marketakrutska Ano, je to tak.

**Comment by marketakrutska** [comment]
Dobře, díky moc, funguje mi to. Issue uzavírám.
