### ISSUE TITLE
Pomalé načítání seznamu sbírek v admin rozhraní

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-admin-client#40]
Načtení seznamu sbírek trvá v admin rozhraní testovací K7 MZK cca 20 sekund, což je nepřiměřeně dlouho ve srovnání s rychlostí, s jakou zobrazuje seznam sbírek web klient. Ten teda nezobrazuje podsbírky, ale i tak je to hodně velký rozdíl.

**Comment by pavel-stastny** [comment]
@zabak Toto již bylo řešeno v rámci #31.  Zatím je to komitnuto ale není nevydaná verze.

**Comment by zabak** [comment]
OK, zde zavírám
