### ISSUE TITLE
Správa procesů - přehlednější zobrazení běžících procesů

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-admin-client#42]
- [x] Zobrazit časy spouštění a ukončení jako 24 hodinový čas a ne 12 hodinový bez am/pm - je to matoucí, vypadá to jako by proces proběhl dřív než byl naplánovaný.
- [x] Pokud se proces skládá z více částí a jedna proběhla a další je naplánovaná, tak by se proces neměl zobrazovat se stavem "běží" ale se stavem "čeká" (správnější by možná bylo "naplánováno", ale chceme to odlišit od procesů, které ještě ani nezačaly.
- [x] Celkový čas trvání procesu skládajícího se z více částí sestává z vlastního provedení akce a z čekání. Bylo by dobré dobu trvání zobrazit jako celkovou dobu trvání a čistý čas běhu procesů.
- [x] Proces který se skládá z více částí z nichž jedna proběhla a další ne by měl mít zobrazený jen čas spuštění první části a čas ukončení poslední části by měl být prázdný, teď se zobrazuje jen čas spuštění a ukončení první části i když proces běží, což je zavádějící. U dokončených procesů se to zobrazuje správně.
- [x] barva stavů jednotlivých částí procesu by měla odpovídat barvě používané pro celé procesy. Teď pokud proces běží, tak i stavy jeho části jsou zobrazeny modře, i když jedna část je dokončena, druhá naplánována apod.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/811537/199350823-d5886013-3492-4850-8055-4af2fca9fcf7.png">

**Comment by kerschfilip** [comment]
ještě doplním, že pokud jedna z částí procesu proběhne s varováním, měl by celkový stav procesu být také varování, nyní se špatně zobrazuje jako chyba:
![image](https://user-images.githubusercontent.com/57805328/199546086-d852a148-26db-4539-b0b5-9db10349f217.png)

**Comment by pkudela** [comment]
1., 4., 5. - vyreseno. 5. souvisi s issue #67 

@pavel-stastny prosim o doreseni bodu 2 a 3, dik

**Comment by pavel-stastny** [comment]
@pkudela @kerschfilip Popdora stavu WARNING pro davku resena komitem do jádra [61230eb](https://github.com/ceskaexpedice/kramerius/commit/61230eb579b2a2f12d4da26217033859d23d0d90)

**Comment by pavel-stastny** [comment]
@zabak 
> Celkový čas trvání procesu skládajícího se z více částí sestává z vlastního provedení akce a z čekání. Bylo by dobré dobu trvání zobrazit jako celkovou dobu trvání a čistý čas běhu procesů.

Pokud je v dávce víc procesů, jsou nyní v tabulce obě hodnoty  
![image](https://user-images.githubusercontent.com/675753/232755727-9a82a5fd-36e5-4ead-bd0d-ccd0d50faba8.png)

**Comment by pkudela** [comment]
Nasazeno na testovacim serveru -> https://admin.k7.inovatika.dev

**Comment by pavel-stastny** [comment]
@zabak @kerschfilip Může se zavřít?

**Comment by kerschfilip** [comment]
za mě je to OK, díky

**Comment by zabak** [comment]
OK, zavírám. Kdybychom ještě na něco narazili, založíme nové issue.
