### ISSUE TITLE
Editace informačních textů v klientovi

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius-admin-client#46]
Bylo by super, kdyby bylo možné editovat všechny nutné kurátorské texty bez toho, aby kurátor musel pro tyhle úkony zatěžovat programátora nebo to složitě nějak sám přepisovat na serveru. Z hlavy mě napadá:

Karta Informace
Hlášky o neveřejných dokumentech
Editace doporučených dokumentů na úvodní straně

Souvisí jak s web klientem, tak admin klientem.

**Comment by annie-cz** [comment]
Bonus: možnost snadno jako kurátor přidat a popsat další kartu, např. FAQ.

**Comment by pavel-stastny** [comment]
@annie-cz Ad hlášky k neveřejným dokumentům. To se bude řešit jako součást editace lokálních licencí. Resp. přenesení konfigurace licencí z klienta do jádra.

**Comment by annie-cz** [comment]
Další bonus by bylo upravovat rovnou v klientovi jako admin např. i texty k virtuálním sbírkám. Když člověk narazí na chybu, je snazší, když se to dá rovnou z fleku opravit a není nutné to vyhledávat někde mimo v admin klientovi zvlášť.

**Comment by annie-cz** [comment]
Přesunuto sem: https://github.com/ceskaexpedice/kramerius-web-client/issues/642.
