### ISSUE TITLE
Indexace --> model - přidat checkbox

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius-admin-client#58]
Bylo by prosím možné přidat do hromadné indexace podle modelu možnost zaškrtnout pomocí checkboxu vice titulů? Takhle se musí každý titul spouštět zvlášť, což je s tím odsouhlasováním poměrně zdlouhavé, nebo se musí spustit všechno.

Díky!

**Comment by pavel-stastny** [comment]
@pkudela Prosim, dodat checkboxy do hlavicky tabulky a do radku.

**Comment by pkudela** [comment]
hovovo, @pavel-stastny s timto issue jsem provedl zmeny, jak jsme se domluvili:

- doplneni checkboxu
- zmena nazvu tlacitek
- odstraneni tlacitka "indexovat" z radku tabulky (nyni neni potreba)
- odstraneni tlacitka vpravo nad tabulkou
- doplneni paginace
- doplneni alertu, pokud je 0 zaznamu v tabulce

Prosim je nutne, abys udelal toto:

- napojit funkcionalitu checkboxu na tlacitko "Indexovat vybrany objekt"
- zprovoznil paginaci

**Comment by pkudela** [comment]
Nasazeno na testovacim serveru -> https://admin.k7.inovatika.dev

**Comment by pkudela** [comment]
@pavel-stastny koukam na to a je to zadratovane v ts, nemelo by to byt soucasti konfigurace? Pokud ano, dej vedet a ja to udelam.

**Comment by pavel-stastny** [comment]
@pkudela To je pozůstatek z minulosti.  Změníme tak, že všechny modely bude podávat jádro.

**Comment by pavel-stastny** [comment]
@kerschfilip Issue zavřeme a na roletku modely vytvoříme nové?
