### ISSUE TITLE
Lidsky srozumitelná jména uživatelů z keycloaku

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius-admin-client#6]
Uživatelé z keycloaku lezou v podobě _keycloack_65a41df9... 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/811537/155222985-e4fbbab4-aae8-4371-b751-4cf69de10b30.png">

Jednak je tam překlep má být keycloak a ne keycloack a hlavně by tam mělo být nějaké lidštější jméno s tím že id uživatele může být v tooltipu.

**Comment by honza-rychtar** [comment]
Jo jo, tohle už se opravuje.

**Comment by honza-rychtar** [comment]
Už je opraveno.

**Comment by pavel-stastny** [comment]
@zabak Myslím, že můžeme uzavřít.
