### ISSUE TITLE
Otevírání detailu procesu v novém tabu

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-admin-client#64]
Udělat čísla procesů jako odkazy, aby šly otevírat v novém panelu.
<img width="1115" alt="Snímek obrazovky 2023-02-22 v 18 53 55" src="https://user-images.githubusercontent.com/1178142/220714609-6172329b-861c-480e-914d-664024914e1f.png">

**Comment by pkudela** [comment]
Nasazeno na k7.inovatika.dev, prosim, otestujte a potvrdte pozadovanou funkcnost.
