### ISSUE TITLE
Odkazování na objekt

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius-admin-client#66]
Původně bylo url pro administraci konkrétního objektu s uuid UUID
```/object/UUID```

Teď se to změnilo na 
```/object/actions/UUID```

Tím přestalo fungovat odkazování z uživatelského klienta na objekt.

Struktura url je teď 
```/object/CATEGROY/UUID```
kde `CATEGORY` je jedno z actions, accssibility, in-collections, other

Lepší by to bylo 
```/object/UUID/CATEGROY```

Zároveň by se 
```/object/UUID```
přesměrovalo na první záložku, na kterou má uživatel práva.

Tohle by vyřešilo i to, že by zase fungovaly ty původní linky používané v klientovi.

**Comment by pkudela** [comment]
hotovo, nasazeno na dev serveru @honza-rychtar prosim otestuj
