### ISSUE TITLE
špatné obarvení stavu procesů v dávkách

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius-admin-client#67]
Stav procesu (taky dávky) se obarvuje ve stylu: ok zeleně, chyba červeně, běží modře.
Barvy stavů procesů se nově vyhodnocují špatně a to podle stavu dávky, ne procesu.
Např:
<img width="851" alt="Snímek obrazovky 2023-03-02 v 12 03 39" src="https://user-images.githubusercontent.com/4635032/222411560-a290f0e1-3ed2-42d6-b228-6586fbfb6398.png">
nebo:
<img width="862" alt="Snímek obrazovky 2023-03-02 v 12 03 04" src="https://user-images.githubusercontent.com/4635032/222411672-cd89708b-09e6-49e2-b169-eaa7d05a5568.png">

**Comment by honza-rychtar** [comment]
@pkudela tohle je na tebe.

**Comment by pkudela** [comment]
ok

**Comment by rzeh4n** [comment]
@pkudela Dá se k tomu pěkně použít ten testovací proces (dev mod), když nastavíš hodně procesů v dávce a konečný stav na random.

**Comment by pkudela** [comment]
Dilky, to se hodi!

**Comment by pkudela** [comment]
fixed, az bude k testovani na serveru dam vedet

**Comment by pkudela** [comment]
Nasazeno na testovacim serveru -> https://admin.k7.inovatika.dev
