### ISSUE TITLE
Odkazování na objekt

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-admin-client#70]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/16591052/223731791-65c133eb-b619-4138-be53-c740c302b3f3.png">

**Comment by honza-rychtar** [comment]
@pkudela To už jsem přepisoval sem Odkazování na objekt #66

**Comment by pkudela** [comment]
@honza-rychtar aha, to jsem nevedel, issue mazu a okomentuju tam, dik.
