### ISSUE TITLE
Implementovat Drag & Drop funkcionalitu pro zmenu poradi licenci

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-admin-client#90]
Implementovat Drag & Drop funkcionalitu pro zmenu poradi licenci a tim sjednotit chovani jako je u zmeny poradi dokumentu ve sbirkach.

**Comment by pkudela** [comment]
- [x] implementovat funkcionalitu drag & drop
- [x] prizpusobit / upravit html, scss, material override
- [x] vytvorit button pro vyvolani dialogu pro naplanovani procesu reindexace (aktivni pouze pokud je zmeneno poradi)
- [x] vytvorit dialog pro spusteni procesu s info hlaskou
- [x] pripravit potrebnou metodu pro spusteni indexace a presmerovani na zvoleny route
- [x] pripravit snackbary s info hlaskou
- [x] provest lokalizaci vsech souvisejicich component
- [ ] implementovat funkcionalitu pro indexaci do pripravene metody

**Comment by pkudela** [comment]
Pripraveno, @pavel-stastny prosim o provedeni posledniho bodu.

**Comment by pavel-stastny** [comment]
Hotovo
