### ISSUE TITLE
Sprava opravneni - odstraneni parametru vraci nespravou chybu v pripade, ze je nekde pouzit

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/kramerius-admin-client#94]
V pripade, ze je parametr nekde pouzit a chci ho ze zalozky "Parametry" odstranit, vrati to chybu 500, melo by to vratit chybu 409. Na strane klienta osetreno, prosim @pavel-stastny o upravu na strane api.

**Comment by pavel-stastny** [comment]
Issue na jádro, zde zavírám.  Viz issue [986](https://github.com/ceskaexpedice/kramerius/issues/986)
